name: Build and Release PDF
on: 
  push:
    tags:
    - '*' 
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make all
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "lecture-notes.pdf,chapters/*.pdf"
          artifactContentType: application/pdf
