name: Build and Release PDF
on: 
  push:
    tags:
    - '*' 
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: lecture-notes.tex
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "lecture-notes.pdf"
